Homework4
zylvis/CSolutionsHW pull request #4
Opened 2022-01-28 23:06 UTC by zylvis

2022-02-01 19:00 UTC, radislavkireev requested changes

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +    public class MatrixEventArgs<T> : EventArgs
please move to separate file

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +            get; set;
make setter private

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +        public T? OldValue { get; set; }
move this property to MatrixTracker class

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +        public T[] DiagonalElements { get; set; }
make property private

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +            }
setter should be as well. 
requirements:

> 
> If i is not equal to j: when reading, the default
> value for type T is returned, and when writing, nothing happens.

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +                OnElementChanged(index, newValue);
Move the code of event triggering to indexer setter. 
Use .Equals for comparing equality instead of custom delegate

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixExtensions.cs
> +            return Addition(a, b);
addition should be a delegate that adds 2 elements of matrix, not whole matrices. 
Requirements: 
> perform the addition
> of two elements of type T (this is a function with two parameters).

2022-02-01 19:00 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixTracker.cs
> +            Matrix = matrix;
subscribe to Matrix.ElementChanged event here. 
Event handler should be a method of MatrixTracker.
Event handler should keep received event arguments as field of MatrixTracker.
Undo method should use kept event arguments and restore previous values of the matrix element, calling Matrix indexer set.

2022-02-12 10:59 UTC, radislavkireev requested changes

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +                        OnElementChanged(i, value);
The event should be triggered after change, so swap lines 64/65

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +        public T? OldValue { get; set; }
Drop this property. 
See comments below for details

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/Matrix.cs
> +                        OldValue = DiagonalElements[i];
keep oldValue in a variable instead of public property
```suggestion
                        var oldValue = DiagonalElements[i];
```

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixExtensions.cs
> +        public static Matrix<T> Add<T>(this Matrix<T> a, Matrix<T> b, Func< T, T, T> Addition)
lowercase 
**a**ddition

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixExtensions.cs
> +                matrix[i, i] = Addition(a[i, i], b[i, i]);
consider the case when matrixes have different sizes

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixTracker.cs
> +        public T? OldValue { get; set; }
make it private

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixTracker.cs
> +        public Matrix<T> Matrix { get; set; }
make it private

2022-02-12 10:59 UTC, radislavkireev commented on Homework4/DiagonalMatrixT/MatrixTracker.cs
> +            Matrix[oldIndex, oldIndex] = OldValue;
If Undo called when no elements were changed at all, then method overrides first element to null. 
Avoid that.

2022-02-13 06:18 UTC, zylvis commented on Homework4/DiagonalMatrixT/Matrix.cs
> +                        OldValue = DiagonalElements[i];
I can't I use this value in line 79

2022-02-16 10:59 UTC, radislavkireev approved these changes

2022-02-16 14:04 UTC, merged